site_name: How to Document
site_description: Simple and clean documentation guide on how to document new and past repositories on Safe Solution.
site_url: https://how-to-document.dev
site_author: Jonathan Motta
repo_url: https://github.com/Safe-Solutions-Engenharia/documentation-default
repo_name: Safe-Solutions-Engenharia/documentation-default

nav:
  - Home: index.md
  - Setup Guide: setup.md
  - Deploy Example: deploy-example.md

theme:
  name: material
  font:
    text: Roboto
    code: Red Hat Mono
  logo: assets/logo_safe.png
  favicon: assets/logo_safe.ico
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: green
      accent: deep orange

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Safe-Solutions-Engenharia
    - icon: fontawesome/brands/twitter
      link: https://x.com/SafeSolutionsBR
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/safe-solutions-engenharia/

copyright: |
  &copy; 2024 <a href="https://github.com/Safe-Solutions-Engenharia"  target="_blank" rel="noopener">Safe Solutions Engenharia</a>